export const API_ENDPOINTS = {
  dashboard: {
    kpis: '/dashboard/kpis',
    revenueTrend: '/dashboard/revenue-trend',
    metaFunnel: '/dashboard/meta-funnel',
    campaigns: '/dashboard/campaigns',
    topProducts: '/dashboard/top-products',
    logistics: '/dashboard/logistics',
    abandonedCarts: '/dashboard/abandoned-carts',
    reviewsSummary: '/dashboard/reviews-summary',
    topRatedProducts: '/dashboard/top-rated-products',
    recentReviews: '/dashboard/recent-reviews',
    allReviews: '/dashboard/all-reviews',
    recentOrders: '/dashboard/recent-orders',
    reviewsTrend: '/dashboard/reviews-trend',
    revenueVsSpend: '/dashboard/revenue-vs-spend',
  },
  analytics: {
    netRevenue: '/analytics/net-revenue',
    rtoByState: '/analytics/rto-by-state',
    geoRevenue: '/analytics/geo-revenue',
    logisticsCosts: '/analytics/logistics-costs',
    customerOverview: '/analytics/customer-overview',
    customerSegments: '/analytics/customer-segments',
    topCustomers: '/analytics/top-customers',
marketingTrend: '/analytics/marketing-trend',
    attributionGap: '/analytics/attribution-gap',
    topSkus: '/analytics/top-skus',
    channelRevenue: '/analytics/channel-revenue',
    creativeFatigue: '/analytics/creative-fatigue',
    returnReasons: '/analytics/return-reasons',
  },
  ga4: {
    summary:   '/analytics/ga4/summary',
    overview:  '/analytics/ga4/overview',
    channels:  '/analytics/ga4/channels',
    ecommerce: '/analytics/ga4/ecommerce',
    products:  '/analytics/ga4/products',
    realtime:  '/analytics/ga4/realtime',
    realtimeWidget: '/analytics/ga4/realtime-widget',
    countryActiveUsers: '/analytics/ga4/country-active-users',
    pagesScreens: '/analytics/ga4/pages-screens',
  },
  finance: {
    kpis: '/finance/kpis',
    revenueBreakdown: '/finance/revenue-breakdown',
    salesBreakdown: '/finance/sales-breakdown',
    paymentMethodSplit: '/finance/payment-method-split',
    payouts: '/finance/payouts',
    payoutDetail: (id: number | string) => `/finance/payouts/${id}`,
    refunds: '/finance/refunds',
    refundsSummary: '/finance/refunds/summary',
    transactions: '/finance/transactions',
  },
  catalog: {
    kpis: '/catalog/kpis',
    products: '/catalog/products',
    productDetail: (id: number | string) => `/catalog/products/${id}`,
    bestSellers: '/catalog/best-sellers',
    slowMovers: '/catalog/slow-movers',
    inventory: '/catalog/inventory',
    stockouts: '/catalog/stockouts',
    margin: '/catalog/margin',
    locations: '/catalog/locations',
  },
  marketing: {
    kpis: '/marketing/kpis',
    discountCodes: '/marketing/discount-codes',
    codePerformance: (code: string) => `/marketing/discount-codes/${encodeURIComponent(code)}/performance`,
    priceRules: '/marketing/price-rules',
    giftCards: '/marketing/gift-cards',
  },
  risk: {
    kpis: '/risk/kpis',
    activeDisputes: '/risk/disputes/active',
    disputes: '/risk/disputes',
  },
  health: '/health',
  sync: {
    shopify: '/sync/shopify',
    meta: '/sync/meta',
    ithink: '/sync/ithink',
  },
} as const;
